insert into trainer.exercises (name, muscle_group, equipment, kind)
select v.name, v.muscle_group, v.equipment, v.kind
from (values
  ('Press de banca con barra','Pecho','Barra','fuerza'),
  ('Press de banca inclinado con mancuernas','Pecho','Mancuernas','fuerza'),
  ('Press de banca declinado con barra','Pecho','Barra','fuerza'),
  ('Aperturas con mancuernas en banco plano','Pecho','Mancuernas','fuerza'),
  ('Cruces en polea alta','Pecho','Polea','fuerza'),
  ('Fondos en paralelas','Pecho','Peso corporal','fuerza'),
  ('Flexiones de pecho','Pecho','Peso corporal','fuerza'),
  ('Press de pecho en maquina sentado','Pecho','Maquina','fuerza'),
  ('Aperturas en maquina contractora','Pecho','Maquina','fuerza'),
  ('Dominadas pronas (agarre prono)','Espalda','Peso corporal','fuerza'),
  ('Dominadas supinas (chin-ups)','Espalda','Peso corporal','fuerza'),
  ('Jalon al pecho en polea','Espalda','Polea','fuerza'),
  ('Remo con barra (pendlay/encorvado)','Espalda','Barra','fuerza'),
  ('Remo con mancuerna a una mano','Espalda','Mancuernas','fuerza'),
  ('Remo en polea baja sentado (gironda)','Espalda','Polea','fuerza'),
  ('Remo en maquina sentado (apoyo pectoral)','Espalda','Maquina','fuerza'),
  ('Jalon al pecho con agarre cerrado neutro','Espalda','Polea','fuerza'),
  ('Pull-over con mancuerna en banco','Espalda','Mancuernas','fuerza'),
  ('Peso muerto convencional con barra','Espalda','Barra','fuerza'),
  ('Press militar con barra','Hombro','Barra','fuerza'),
  ('Press de hombro con mancuernas','Hombro','Mancuernas','fuerza'),
  ('Press Arnold','Hombro','Mancuernas','fuerza'),
  ('Elevaciones laterales con mancuernas','Hombro','Mancuernas','fuerza'),
  ('Elevaciones frontales con mancuernas','Hombro','Mancuernas','fuerza'),
  ('Pajaro con mancuernas','Hombro','Mancuernas','fuerza'),
  ('Face pull en polea','Hombro','Polea','fuerza'),
  ('Remo al menton con barra','Hombro','Barra','fuerza'),
  ('Curl con barra de pie','Biceps','Barra','fuerza'),
  ('Curl con mancuernas alterno','Biceps','Mancuernas','fuerza'),
  ('Curl martillo con mancuernas','Biceps','Mancuernas','fuerza'),
  ('Curl concentrado','Biceps','Mancuernas','fuerza'),
  ('Curl predicador con barra Z','Biceps','Maquina','fuerza'),
  ('Curl en polea baja','Biceps','Polea','fuerza'),
  ('Extension de triceps en polea con cuerda','Triceps','Polea','fuerza'),
  ('Press frances con barra Z tumbado','Triceps','Barra','fuerza'),
  ('Patada de triceps con mancuerna','Triceps','Mancuernas','fuerza'),
  ('Press cerrado con barra en banco','Triceps','Barra','fuerza'),
  ('Sentadilla con barra','Cuadriceps','Barra','fuerza'),
  ('Sentadilla goblet','Cuadriceps','Mancuernas','fuerza'),
  ('Sentadilla frontal con barra','Cuadriceps','Barra','fuerza'),
  ('Prensa de piernas','Cuadriceps','Maquina','fuerza'),
  ('Zancadas con mancuernas','Cuadriceps','Mancuernas','fuerza'),
  ('Extension de cuadriceps en maquina','Cuadriceps','Maquina','fuerza'),
  ('Sentadilla bulgara','Cuadriceps','Mancuernas','fuerza'),
  ('Subida al cajon con mancuernas','Cuadriceps','Mancuernas','fuerza'),
  ('Sentadilla isometrica en pared','Cuadriceps','Peso corporal','fuerza'),
  ('Peso muerto rumano con barra','Femoral','Barra','fuerza'),
  ('Peso muerto rumano a una pierna con mancuerna','Femoral','Mancuernas','fuerza'),
  ('Curl femoral tumbado en maquina','Femoral','Maquina','fuerza'),
  ('Curl femoral sentado en maquina','Femoral','Maquina','fuerza'),
  ('Hip thrust con barra','Gluteo','Barra','fuerza'),
  ('Puente de gluteo en el suelo','Gluteo','Peso corporal','fuerza'),
  ('Patada de gluteo en polea','Gluteo','Polea','fuerza'),
  ('Buenos dias con barra','Femoral','Barra','fuerza'),
  ('Abduccion de cadera en maquina','Gluteo','Maquina','fuerza'),
  ('Elevacion de talones de pie en maquina','Gemelo','Maquina','fuerza'),
  ('Elevacion de talones sentado con mancuernas','Gemelo','Mancuernas','fuerza'),
  ('Elevacion de talones en prensa','Gemelo','Maquina','fuerza'),
  ('Encogimientos de trapecio con barra','Trapecio','Barra','fuerza'),
  ('Encogimientos de trapecio con mancuernas','Trapecio','Mancuernas','fuerza'),
  ('Curl de muñeca con barra','Antebrazo','Barra','fuerza'),
  ('Paseo del granjero con mancuernas','Antebrazo','Mancuernas','fuerza'),
  ('Plancha abdominal (frontal)','Core','Peso corporal','fuerza'),
  ('Plancha lateral','Core','Peso corporal','fuerza'),
  ('Crunch abdominal','Core','Peso corporal','fuerza'),
  ('Elevacion de piernas colgado','Core','Barra','fuerza'),
  ('Rueda abdominal (ab wheel)','Core','Maquina','fuerza'),
  ('Russian twist (giro ruso)','Core','Mancuernas','fuerza'),
  ('Mountain climbers (escaladores)','Core','Peso corporal','fuerza'),
  ('Hollow hold (mantenimiento en hueco)','Core','Peso corporal','fuerza'),
  ('Pallof press (press anti-rotacion en polea)','Core','Polea','fuerza'),
  ('Estiramiento de pectoral en marco de puerta','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de dorsal con brazo en alto','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de hombro cruzado','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de triceps por encima de la cabeza','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de biceps con brazo extendido atras','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de cuello lateral','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de trapecio superior','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de antebrazo flexor con palma arriba','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de antebrazo extensor con palma abajo','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de cuádriceps de pie','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de isquiotibiales sentado','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de glúteo tumbado (figura cuatro)','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de gemelo contra la pared','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de flexores de cadera en zancada','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de aductores en mariposa','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de piramidal sentado (cruce de pierna)','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento lumbar de rodillas al pecho','Estiramiento','Peso corporal','estiramiento'),
  ('Estiramiento de isquiotibiales de pie con pierna elevada','Estiramiento','Peso corporal','estiramiento'),
  ('Rotaciones de cadera','Movilidad','Peso corporal','movilidad'),
  ('Circulos de hombro','Movilidad','Peso corporal','movilidad'),
  ('Gato-vaca','Movilidad','Peso corporal','movilidad'),
  ('Rotacion toracica en cuadrupedia','Movilidad','Peso corporal','movilidad'),
  ('Balanceo de piernas','Movilidad','Peso corporal','movilidad'),
  ('Sentadilla profunda con movilidad','Movilidad','Peso corporal','movilidad'),
  ('World''s greatest stretch','Movilidad','Peso corporal','movilidad'),
  ('Dislocaciones de hombro con banda','Movilidad','Banda','movilidad'),
  ('Hiperextensiones en banco romano (extensión de espalda 45º)','Femoral','Maquina','fuerza'),
  ('Remo en barra T','Espalda','Barra','fuerza'),
  ('Remo invertido con peso corporal','Espalda','Peso corporal','fuerza'),
  ('Press de hombro en maquina sentado','Hombro','Maquina','fuerza'),
  ('Extension de triceps por encima de la cabeza con mancuerna','Triceps','Mancuernas','fuerza'),
  ('Fondos de triceps en banco','Triceps','Peso corporal','fuerza'),
  ('Curl de muñeca invertido con barra','Antebrazo','Barra','fuerza'),
  ('Peso muerto sumo con barra','Gluteo','Barra','fuerza'),
  ('Sentadilla hack en maquina','Cuadriceps','Maquina','fuerza'),
  ('Zancada hacia atras con mancuernas','Cuadriceps','Mancuernas','fuerza'),
  ('Dead bug (bicho muerto)','Core','Peso corporal','fuerza'),
  ('Postura del niño (child''s pose)','Estiramiento','Peso corporal','estiramiento'),
  ('Movilidad de tobillo en pared (dorsiflexion)','Movilidad','Peso corporal','movilidad'),
  ('Movilidad de cadera 90/90','Movilidad','Peso corporal','movilidad')
) as v(name, muscle_group, equipment, kind)
where not exists (select 1 from trainer.exercises e where lower(e.name)=lower(v.name));
